#!/bin/sh
 
# Base Variables

ORACLE_BASE="/opt/oracle"
export ORACLE_BASE

ORACLE_INVENTORY_HOME="${ORACLE_BASE}/oraInventory"
export ORACLE_INVENTORY_HOME

ORACLE_INVENTORY_PTR="/etc/oraInst.loc"
export ORACLE_INVENTORY_PTR

# Staging Variables

STAGING_DIRECTORY="/opt/software"
export STAGING_DIRECTORY

# GEOS Variables

TARGET_ENVIRONMENT="lab"
export TARGET_ENVIRONMENT

FUNCTIONAL_BLOCK_NAME="osb01"
export FUNCTIONAL_BLOCK_NAME

BUILDING_BLOCK_NAME="osb02"
export BUILDING_BLOCK_NAME

BB_FULL_NAME="${TARGET_ENVIRONMENT}_${FUNCTIONAL_BLOCK_NAME}_${BUILDING_BLOCK_NAME}"
export BB_FULL_NAME

BUILDING_BLOCK_VERSION="12.2"
export BUILDING_BLOCK_VERSION

BUILDING_BLOCK_HOME="${ORACLE_BASE}/${FUNCTIONAL_BLOCK_NAME}/${BUILDING_BLOCK_NAME}/${BUILDING_BLOCK_VERSION}"
export BUILDING_BLOCK_HOME

BUILDING_BLOCK_USER="oracle"
export BUILDING_BLOCK_USER

BUILDING_BLOCK_GROUP="oracle"
export BUILDING_BLOCK_GROUP

OID_ADDRESS=10.91.238.64
export OID_ADDRESS

OID_PORT=20391
export OID_PORT

OVD_PORT=6501
export OVD_PORT


# Available types:
#     INFRA : Infrastructure
#     SOA   : SOA Suite
#     OSB   : Service BUS
#     BAM   : Business Analytic
#     BPM   : Business Process
INSTALL_TYPE='OSB'
export INSTALL_TYPE

# FMW Variables

MIDDLEWARE_HOME="${BUILDING_BLOCK_HOME}/fmw"
export MIDDLEWARE_HOME

# DB Variables
export DB_CONNECTION_STRING="10.91.220.197:1521/fmw.labdbs01.mw.lab.geos.loc"
SYSDBA_USER="SYS"